services:
  db:
    image: postgres:15
    container_name: backend-server-postgres-1
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: task_management
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend # Trỏ vào folder đã đổi tên
    container_name: nest-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=task_management
      - JWT_SECRET=TopSecretKey123!
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build: ./frontend-next # Đã đổi sang folder Next.js
    container_name: nextjs-frontend
    ports:
      - '80:3000' # Map cổng 80 của máy host vào cổng 3000 của container Next.js
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000 # URL Backend khi chạy ở Client (Browser)
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  dbdata:
