services:
  db:
    image: postgres:15
    container_name: backend-server-postgres-1
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: task_management
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend # Trỏ vào folder đã đổi tên
    container_name: nest-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=db # Trỏ vào tên service db ở trên
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin123
      - DB_DATABASE=task_management
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend # Trỏ vào folder đã đổi tên
    container_name: react-frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  dbdata: